CREATE MULTISET TABLE R_ST ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      LXOID INTEGER TITLE 'lxOid' NOT NULL,
      EDW_SRC_SYS_NM VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'EDW Source System Name' NOT NULL,
      MXOID INTEGER TITLE 'mxOid' NOT NULL,
      ID VARCHAR(255) CHARACTER SET UNICODE NOT CASESPECIFIC TITLE 'id' NOT NULL,
      LXTYPE INTEGER TITLE 'lxType' NOT NULL
      )
